import math
from datetime import datetime, date, timedelta, timezone
from sqlalchemy.orm import Session
from app.models.work_session import WorkSession
from app.models.habit import HabitRecord
from app.models.financial import FinancialRecord
from app.services.activity import log_activity

ACTIVITIES = ["Coding", "Study", "Project", "Reading", "Meeting", "Other"]

def seed_synthetic_12week_dataset(db: Session, user_id: int):
    """
    Generates 84 days (12 weeks) of realistic synthetic demo data
    for testing productivity analytics, heatmaps, habit streaks, and forecasting models.
    All created rows have `is_demo = True` and are clearly marked.
    """
    # Delete only rows previously generated by this demo generator.
    # Real user data is never removed.
    db.query(WorkSession).filter(WorkSession.user_id == user_id, WorkSession.is_demo.is_(True)).delete(synchronize_session=False)
    db.query(HabitRecord).filter(HabitRecord.user_id == user_id, HabitRecord.is_demo.is_(True)).delete(synchronize_session=False)
    db.query(FinancialRecord).filter(FinancialRecord.user_id == user_id, FinancialRecord.is_demo.is_(True)).delete(synchronize_session=False)
    db.commit()

    now_utc = datetime.now(timezone.utc)
    # Generate exactly 12 complete calendar weeks (84 days), ending on the
    # most recent Sunday. This avoids partial-week observations in forecasting.
    end_date = now_utc.date() - timedelta(days=(now_utc.weekday() + 1) % 7)
    start_date = end_date - timedelta(days=83)

    sessions_to_add = []
    habits_to_add = []
    financial_to_add = []

    for day_idx in range(84):
        current_date = start_date + timedelta(days=day_idx)
        dt_start_base = datetime(current_date.year, current_date.month, current_date.day, 9, 0, tzinfo=timezone.utc)
        weekday = current_date.weekday() # 0 = Monday, 6 = Sunday

        # Weekend vs Weekday patterns with realistic upward trend
        trend_factor = 1.0 + (day_idx / 84.0) * 0.35 # 35% growth over 12 weeks
        is_weekend = weekday >= 5

        if is_weekend:
            # 1 to 2 sessions on weekend
            session_types = ["Reading", "Study"]
            durations = [int(45 * trend_factor), int(60 * trend_factor)]
        else:
            # 3 to 4 sessions on weekday
            session_types = ["Coding", "Study", "Project", "Meeting"]
            durations = [int(90 * trend_factor), int(60 * trend_factor), int(75 * trend_factor), int(30 * trend_factor)]

        t_offset = 0
        for act, dur in zip(session_types, durations):
            s_time = dt_start_base + timedelta(minutes=t_offset)
            e_time = s_time + timedelta(minutes=dur)
            sessions_to_add.append(WorkSession(
                user_id=user_id,
                activity_type=act,
                started_at=s_time,
                ended_at=e_time,
                duration_minutes=dur,
                status="completed",
                notes=f"[DEMO/SYNTHETIC] Automated {act} session",
                is_demo=True,
                created_at=s_time
            ))
            t_offset += dur + 15 # 15 min break

        # Habit tracking pattern
        if day_idx % 2 == 0 or weekday < 5:
            habits_to_add.append(HabitRecord(
                user_id=user_id,
                habit_name="[DEMO] Daily Technical Reading",
                completed=True,
                duration="30 mins",
                frequency="Daily",
                is_demo=True,
                recorded_at=current_date,
                created_at=dt_start_base
            ))

        # Financial entries every 2 weeks
        if day_idx % 14 == 0:
            financial_to_add.append(FinancialRecord(
                user_id=user_id,
                income=4200.0 if day_idx % 28 == 0 else 650.0,
                expenses=1100.0 + (day_idx * 5),
                savings=1400.0,
                budget=4200.0,
                expense_category="Salary" if day_idx % 28 == 0 else "Freelance",
                financial_goal="[DEMO/SYNTHETIC DATA] Bi-weekly ledger",
                is_demo=True,
                recorded_at=current_date,
                created_at=dt_start_base
            ))

    db.add_all(sessions_to_add)
    db.add_all(habits_to_add)
    db.add_all(financial_to_add)
    db.commit()

    log_activity(
        db,
        user_id=user_id,
        activity_type="DEMO_DATA_GENERATED",
        description="Generated 12-week (84 daily observations) synthetic demo dataset for predictive analytics."
    )

    return {
        "status": "success",
        "days_seeded": 84,
        "sessions_created": len(sessions_to_add),
        "message": "DEMO / SYNTHETIC DATA successfully generated for 12-week time-series analysis."
    }
